config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'places#index'

  resources :places, except: [:show] do
    resources :posts
  end

  resources :categories, only: [:show]

  resources :posts do
    resources :guesses, except: [:index, :show, :update]
    resources :tags, only: [:create]
  end

  resources :guesses, except: [:index, :show] do
    member do
      post "increase_score"
      post "decrease_score"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tags
  has_many :posts, through: :tags
end

app/models/guess.rb
class Guess < ApplicationRecord
  default_scope { order('score DESC') }
  belongs_to :post
  belongs_to :user
  validates :guess_text, presence: true

  def score_up
    self.score += 1
  end
  def score_down
    self.score -= 1
  end
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :country, :state, :city, :place_photo_url, presence: true

  def us_states
      [
        ['N/A', '-'],
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY']
      ]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :guesses, dependent: :destroy
  belongs_to :place
  has_many :tags, dependent: :destroy
  has_many :categories, through: :tags
  validates :title, :photo_url, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :guesses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @posts = @category.posts
  end
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  def increase_score
    @guess = Guess.find(params[:id])
    @post = @guess.post
    @place = @post.place
    @guess.score_up
    @guess.save
    redirect_to place_post_path(@place, @post)
  end

  def decrease_score
    @guess = Guess.find(params[:id])
    @post = @guess.post
    @place = @post.place
    @guess.score_down
    @guess.save
    redirect_to place_post_path(@place, @post)
  end

  def new
    @post = Post.find(params[:post_id])
    @place = @post.place
    @guess = @post.guesses.new
  end

  def create
    @post = Post.find(params[:post_id])
    @place = @post.place
    @guess = @post.guesses.new(guess_params.merge(user: current_user))
    if @guess.save
      flash[:notice] = 'Comment posted!'
      redirect_to place_post_path(@place, @post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @place = @post.place
    @guess = Guess.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @place = @post.place
    @guess = Guess.find(params[:id])
    if @guess.user == current_user
      @guess.update(guess_params.merge(user: current_user))
      flash[:notice] = 'Comment updated!'
      redirect_to place_post_path(@place, @post)
    else
      flash[:alert] = 'Only OP can update comment!'
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @place = @post.place
    @guess = Guess.find(params[:id])
    if @guess.user == current_user
       @guess.destroy
       flash[:notice] = 'Comment deleted!'
       redirect_to place_post_path(@place, @post)
    else
       flash[:alert] = 'only OP can delete comment'
       redirect_to place_post_path(@place, @post)
    end
  end

  private
  def guess_params
    params.require(:guess).permit(:guess_text)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  #index
  def index
    @places = Place.all
  end

  #new
  def new
    @place = Place.new
  end

  #create
  def create
    @place = Place.new(place_params)
    if @place.save
      flash[:notice] = 'Place Created'
      redirect_to places_path
    else
      render :new
    end
  end

  #edit
  def edit
    @place = Place.find(params[:id])
  end
  #update
  def update
    @place = Place.find(params[:id])
    if @place.update(place_params)
      flash[:notice] = 'Place Updated'
      redirect_to places_path
    else
      render :new
    end
  end
  #destroy
  def destroy
    @place = Place.find(params[:id])
    @place.destroy!
    flash[:alert] = "Place Deleted!"
    redirect_to places_path
  end
  
  private
  def place_params
    params.require(:place).permit(:country, :state, :city, :place_photo_url)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @place = Place.find(params[:place_id])
    @posts = @place.posts.all
  end

  def new
    @place = Place.find(params[:place_id])
    @post = @place.posts.new
  end

  def create
    @place = Place.find(params[:place_id])
    @post = @place.posts.new(post_params)
      if @post.save
        flash[:notice] = 'Post Created'
        redirect_to place_post_path(@place, @post)
      else
        render :new
      end
  end

  def show
    @place = Place.find(params[:place_id])
    @post = @place.posts.find(params[:id])
    @tags = @post.tags
    @tag = Tag.new
  end

  def edit
    @place = Place.find(params[:place_id])
    @post = Post.find(params[:id])
  end

  def update
    @place = Place.find(params[:place_id])
    @post = Post.find(params[:id])
      if @post.update(post_params)
        flash[:notice] = 'Post Updated'
        redirect_to place_posts_path(@place)
      else
        render :new
      end
  end

  def destroy
    @place = Place.find(params[:place_id])
    @post = Post.find(params[:id])
    @post.destroy
    flash[:alert] = "Post Deleted!"
    redirect_to place_posts_path(@place)
  end

  private
  def post_params
    params.require(:post).permit(:title, :photo_url)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @place = @post.place
    @category = Category.find_or_create_by(category_text: params[:category_text])

    existing_tag = Tag.find_by(post: @post, category: @category)

    if !existing_tag
      @post.tags.create(category: @category)
    else
      flash[:alert] = 'Tag already exists'
    end
      redirect_to place_post_path(@place, @post)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/show.html.erb
<%= link_to "&larr; Back".html_safe, :back, :class => 'dropbtn' %>
<div class="tag-show-wrapper">
<div class="tag">

<h3 class='tag-show-content'><%= @category.category_text %></h3>

</div>

<% @posts.each do |post| %>
<h1 class='sub-title'><%= post.title %></h1>

<object data="<%= post.photo_url %>" type="image/png" class="photo">
<img src="https://www.justpro.co/img/no-image.png" class="default-photo"/>
</object>

<br>
<% end %>
</div>

app/views/guesses/_form.html.erb
<%= simple_form_for ([@post, @guess]) do |f| %>

  <%= f.input :guess_text, :input_html => { :class => 'comment-form' }, label: 'Comment', error: 'Enter comment!' %>

  <%= f.button :submit, 'Make comment!' %>

<% end %>

app/views/guesses/edit.html.erb
<%= link_to "&larr; Back".html_safe, place_post_path(@place, @post), :class => 'dropbtn' %>
<%= render 'form' %>

app/views/guesses/new.html.erb
<%= link_to "&larr; Back".html_safe, place_post_path(@place, @post), :class => 'dropbtn' %>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Places</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Questrial" rel="stylesheet">
  </head>
  <body>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
  <footer>
    <div class= 'sig'>
          <p class='signature'>Created 2017 By J.G.</p>
        </div>
  </footer>
</html>

app/views/places/_form.html.erb
<%= simple_form_for @place do |f| %>

 <%= f.input :country, error: 'cant be blank' %>

  <%= f.input :state, collection: @place.us_states %>

  <%= f.input :city %>

  <%= f.input :place_photo_url %>

  <%= f.submit %>

<% end %>

app/views/places/edit.html.erb
<%= link_to "&larr; Back".html_safe, root_path, :class => 'dropbtn' %>

<%= render 'form' %>
<%= link_to 'delete place', place_path(@place), :class => 'dropbtn', method: :delete %>

app/views/places/index.html.erb
<div class="dropdown">
  <button class="dropbtn">Menu</button>
    <div class="dropdown-content">
      <%= link_to 'Add your location!', new_place_path, :class => 'home-links' %>

      <% if !current_user %>
      <%= link_to "Sign Up", new_user_registration_path, :class => 'home-links' %>
      <%= link_to "Sign In", new_user_session_path, :class => 'home-links'  %>
      <% else %>
      <%= link_to "Sign Out", destroy_user_session_path, :class => 'home-links', method: :delete %>
      <% end %>

    </div>
</div>

<div class="place-index-wrapper">
  <h1 class='main-title'>Places</h1>
  <br>

  <% @places.each do |place| %>
  <div class="place-content-wrapper">
  <!--
    Was a little weird to have 3 separate link_to methods for the same link.
    I think it's better to make one link with the text interpolated together
  -->
  <%= link_to "#{place.city} #{place.state} #{place.country}", place_posts_path(place), :class => 'place-links' %>
  <%= link_to '(edit)', edit_place_path(place), :class => 'place-links' %></p>

</div>
<!--
  From a UI perspective, it's preferrable to be able to click on this image
  in addition to the title in order to visit the linked resource/page
-->
<a href="<%= place_posts_path(place) %>"><object data="<%=place.place_photo_url%>" type="image/png" class="photo">
<img src="https://www.justpro.co/img/no-image.png" class="default-photo"/></a>
</object>

<br>
<% end %>
</div>

app/views/places/new.html.erb
<%= link_to "&larr; Back".html_safe, root_path, :class => 'dropbtn' %>

<%= render 'form' %>

app/views/posts/_form.html.erb
<%= simple_form_for ([@place, @post]) do |f| %>

  <%= f.input :title, label: 'post title', error: "can't be blank" %>

  <%= f.input :photo_url, label: 'photo' %>

  <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<%= link_to "&larr; Back".html_safe, place_posts_path(@place), :class => 'dropbtn' %>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= link_to "&larr; Back".html_safe, root_path, :class => 'dropbtn' %>

<div class="dropdown">
  <button class="dropbtn">Menu</button>
<div class="dropdown-content">
  <%= link_to 'New Post', new_place_post_path(@place), :class => 'home-links' %>
  <%= link_to 'Home', root_path, :class => 'home-links' %>

<% if !current_user %>
<%= link_to "Sign Up", new_user_registration_path, :class => 'home-links' %>
<%= link_to "Sign In", new_user_session_path, :class => 'home-links'  %>
<% else %>
<%= link_to "Sign Out", destroy_user_session_path, :class => 'home-links', method: :delete %>
<% end %>

</div>
</div>

<div class="post-index-wrapper">

<% @posts.each do |post| %>
<div class="post-index-wrapper2">
  <p><%= link_to post.title, place_post_path(@place, post), :class => 'post-title' %></p>
  <hr>
  <%= link_to 'Edit post', edit_place_post_path(@place, post), :class => 'edit-delete' %> <span class='slash'>/</span>
  <%= link_to 'Delete post', place_post_path(@place, post), :class => 'edit-delete', method: :delete %>
  <span class='create-date'>Create date: <%= post.created_at %></span>
  <hr>
  <br>
</div>
<!--
  From a UI perspective, it's preferrable to be able to click on this image
  in addition to the title in order to visit the linked resource/page
-->
<a href="<%= place_post_path(@place, post) %>"><object data="<%= post.photo_url %>" type="image/png" class="photo">
<img src="https://www.justpro.co/img/no-image.png" class="default-photo"/>
</object></a>
<% end %>
</div>

app/views/posts/new.html.erb
<%= link_to "&larr; Back".html_safe, place_posts_path(@place), :class => 'dropbtn' %>
<%= render 'form' %>

app/views/posts/show.html.erb
<%= link_to "&larr; Back".html_safe, place_posts_path(@place), :class => 'dropbtn' %>

<div class="dropdown">
  <button class="dropbtn">Menu</button>
<div class="dropdown-content">

<%= link_to 'Add Comment', new_post_guess_path(@post), :class => 'home-links' %>
<%= link_to 'Home', root_path, :class => 'home-links' %>

<% if !current_user %>
<%= link_to "Sign Up", new_user_registration_path, :class => 'home-links' %>
<%= link_to "Sign In", new_user_session_path, :class => 'home-links'  %>
<% else %>
<%= link_to "Sign Out", destroy_user_session_path, :class => 'home-links', method: :delete %>
<% end %>

</div>
</div>

<div class="post-show-wrapper">
<h1 class="sub-title"><%= @post.title %></h1>

<div class="tags">

<% @tags.each do |tag| %>
<%= link_to tag.category.category_text, category_path(tag.category), :class => 'tag-content' %>
<% end %>

</div>
<br>
<object data="<%= @post.photo_url %>" type="image/png" class="photo">
<img src="https://www.justpro.co/img/no-image.png" class="default-photo"/>
</object>


</div>
<br>
<div class="add-tags">

<%= form_for [@post, @tag] do |f| %>
<%= text_field_tag :category_text %>
<%= f.submit "Create Tag" %>
<% end %>

</div>
<br>
<div class="guess-wrapper">

<!--
  Consider adding the guess form directly in the show page. It saves the user an
  extra click from having to visit a separate page.
-->
<% @guess = Guess.new %>
<%= render 'guesses/form' %>

<% @post.guesses.each do |guess| %>
<div class="guesses">
  <p class='guess-text'><%= guess.guess_text %>
    <% if guess.user == current_user %>

    <%= link_to 'edit', edit_post_guess_path(@post, guess), :class => "comment-edit-delete" %>
    <%= link_to 'delete', post_guess_path(@post, guess), :class => "comment-edit-delete", method: :delete %>
    <% end  %>
    <%= link_to "&uarr;".html_safe, increase_score_guess_path(guess), :class => "arrows", method: :post %>
    <%= link_to "&darr;".html_safe, decrease_score_guess_path(guess), :class => "arrows", method: :post %>
    <span class="score"><%= guess.score %></span>
    <p class='guess-created'>Created: <%= guess.created_at %></p>

    </div>
    <br>
<% end %>
</div>